"""Megatron-Core 侧实现：深度连接算子、层与 ``--spec`` 预设。

风格对齐上游 megatron-core（module docstring 讲清"接在哪、为什么"、行内注释给出来源
行号）；本目录由 gdar_package 的 FlagScale 移植件而来，mcore 0.20 适配见各文件顶部注记。

spec 预设在这里是**实打实的模块属性**：mcore 的 ``spec_utils.import_module`` 查
``vars(module)[name]``，走不到 ``__getattr__``，所以 ``--spec`` 只能指到真正有该属性的模块
（``...models.megatron.gdar_spec gdar_layer_spec_paper`` 或 ``...models.megatron <名字>``，
后者由本文件显式 re-export）。导出表由各 spec 模块的 ``__all__`` 生成，加预设时无需手改。
"""

from __future__ import annotations

from .ablation_spec import (  # noqa: F401
    ABLATION_GATE_CHANNELS,
    AblationGdarLayer,
    GATED_AR_BLOCK,
    PAPER_GATE_SPECS,
    gate_selecting_gates,
    gated_ar_layer_spec,
    gated_ar_layer_spec_block12,
    gated_ar_layer_spec_block16,
    gated_ar_layer_spec_block2,
    gated_ar_layer_spec_block6,
    gated_ar_layer_spec_block8,
    gated_ar_layer_spec_decay_erase,
    gated_ar_layer_spec_decay_only,
    gated_ar_layer_spec_erase_only,
    gated_ar_layer_spec_erase_write,
    gated_ar_layer_spec_no_gate,
    gated_ar_layer_spec_scalar,
    gated_ar_layer_spec_write_decay,
    gated_ar_layer_spec_write_only,
    gdar_half_init_layer_spec,
    gdar_paper_gates_d,
    gdar_paper_gates_de,
    gdar_paper_gates_dw,
    gdar_paper_gates_e,
    gdar_paper_gates_ew,
    gdar_paper_gates_none,
    gdar_paper_gates_scalar,
    gdar_paper_gates_w,
    gdar_uniform_init_layer_spec,
    make_ablation_spec,
)

from .depth_spec import (  # noqa: F401
    ar_layer_spec,
    ar_layer_spec_block12,
    ar_layer_spec_block2,
    ar_layer_spec_block4,
    ar_layer_spec_block6,
    ar_layer_spec_block8,
    ar_layer_spec_reference,
    dar_layer_spec,
    dar_layer_spec_block12,
    dar_layer_spec_block2,
    dar_layer_spec_block4,
    dar_layer_spec_block6,
    dar_layer_spec_block8,
    dar_layer_spec_null_source,
    dar_layer_spec_reference,
    dar_layer_spec_reference_block4,
    denseformer_layer_spec,
    denseformer_layer_spec_official,
    denseformer_layer_spec_period4,
    make_depth_spec,
    mudd_layer_spec,
    mudd_layer_spec_official_norm,
    mudd_layer_spec_random,
    mudd_layer_spec_reference,
)

from .gdar_spec import (  # noqa: F401
    DESIGN_ABLATIONS,
    gdar_layer_spec,
    gdar_layer_spec_block16,
    gdar_layer_spec_block2,
    gdar_layer_spec_block4,
    gdar_layer_spec_block4_r16,
    gdar_layer_spec_block4_r64,
    gdar_layer_spec_block8,
    gdar_layer_spec_decay_projected,
    gdar_layer_spec_fullrank,
    gdar_layer_spec_gate_delta,
    gdar_layer_spec_gate_prefix,
    gdar_layer_spec_lambda_free,
    gdar_layer_spec_no_output_route,
    gdar_layer_spec_paper,
    gdar_layer_spec_paper_address_novelty,
    gdar_layer_spec_paper_address_state,
    gdar_layer_spec_paper_b16,
    gdar_layer_spec_paper_b2,
    gdar_layer_spec_paper_b4,
    gdar_layer_spec_paper_b8,
    gdar_layer_spec_paper_carrier0,
    gdar_layer_spec_paper_decay_free,
    gdar_layer_spec_paper_gate_delta,
    gdar_layer_spec_paper_gate_prefix,
    gdar_layer_spec_paper_heads1,
    gdar_layer_spec_paper_init_half,
    gdar_layer_spec_paper_init_paper,
    gdar_layer_spec_paper_init_uniform,
    gdar_layer_spec_paper_ladder0,
    gdar_layer_spec_paper_lambda_free,
    gdar_layer_spec_paper_mix_whitened,
    gdar_layer_spec_paper_no_output_route,
    gdar_layer_spec_paper_noladder,
    gdar_layer_spec_paper_null_off,
    gdar_layer_spec_paper_rank16,
    gdar_layer_spec_paper_rankfull,
    gdar_layer_spec_paper_sublayer,
    gdar_layer_spec_paper_update_reference,
    gdar_layer_spec_paper_whiten_diag,
    gdar_layer_spec_paper_whiten_off,
    gdar_layer_spec_read_whitened_mix,
    gdar_layer_spec_reference,
    gdar_layer_spec_theory,
    gdar_layer_spec_upstream,
    make_gdar_spec,
)

from .hc_spec import (  # noqa: F401
    hc_layer_spec,
    hc_layer_spec_force_identity,
    hc_layer_spec_published,
    make_hc_spec,
    mhc_layer_spec,
    mhc_layer_spec_force_identity,
    mhc_layer_spec_lite,
    mhc_layer_spec_published,
)
